### ISSUE TITLE
US-1:  Switch campus map

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#1]
As a user, I want to easily switch between campuses (SGW and Loyola)

**Associated epic:** #17 

**Tasks:**
- [x] Create button that allows user to toggle between SGW and Loyola campuses on the map

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | User opens the outdoor map | Two buttons are **clearly** displayed on the top of the map to toggle between campuses | 
2 | Click one of the buttons | Map displays designated campus and surrounding area on the outdoor map view | Passed

![image](https://user-images.githubusercontent.com/40539079/74111109-19cc8980-4b60-11ea-9b4a-b5018cf7ebc4.png)

**Comment by samiha-rahman** [comment]
Change color of the buttons to be not transparent @ThierryRomain

**Comment by mosaliza** [comment]
- Button to toggle between the maps should be more visible on the user interface

**Comment by samiha-rahman** [comment]
> * Button to toggle between the maps should be more visible on the user interface

Added to acceptance criteria
