### ISSUE TITLE
Bug-9: Missing "Alt" attribute to image

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#106]
**Description:**
Sonarqube detected the the "Alt" attribute is missing in an HTML image. 
The same bug in two different files:

- src/app/components/building-info/building-info.component.html
![image.png](https://images.zenhubusercontent.com/5e18d0aa32969d7ce10e5f59/ceee960f-7d1d-4031-a868-148d36727d38)
- src/app/components/outdoor-map/outdoor-map.component.html
![image.png](https://images.zenhubusercontent.com/5e18d0aa32969d7ce10e5f59/113e8773-689e-45d1-9796-ee2190cf1315)

**Resolution:**

-  Add "alt" attribute to image

**Reproduce:**

**Expected behaviour:**
Should show alternative if image does not load

**Found in commit:**
- src/app/components/building-info/building-info.component.html
6edb159b3d448faab082621c0e035188669af996
- src/app/components/outdoor-map/outdoor-map.component.html
99982207632df6a551862a846d18b06d9d1e034f

**Resolved in commit:**
3bf1fb2621aacccde44c5869240dd4c8b14e0803

**Comment by samiha-rahman** [comment]
@ThierryRomain could you fix this bug in your PR #99 please?

**Comment by ThierryRomain** [comment]
> @ThierryRomain could you fix this bug in your PR #99 please?

I didn't get around to fixing it at the time, it is included in my next PR

**Comment by ThierryRomain** [comment]
Fixed in PR #141 , commit 3bf1fb2621aacccde44c5869240dd4c8b14e0803
