### ISSUE TITLE
AT-1: Highlight campus buildings

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#117]
As a user, I want to easily distinguish the shapes of campus buildings from city buildings.

Associated story: #2 

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | View buildings belonging to Concordia on outdoor map | Buildings belonging to Concordia will be highlighted with a red overlay | Passed

**Comment by jodavimehran** [comment]
accepted

**Comment by mosaliza** [comment]
Accepted.
