### ISSUE TITLE
US-12: Accessibility Option (for disabled users)

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#12]
As a disabled user, I want to see directions that can accommodate me.

Associated epic:
#20 

Associated tasks:
![image](https://user-images.githubusercontent.com/40539079/74111302-b2afd480-4b61-11ea-964d-5183426f2ac8.png)
![image](https://user-images.githubusercontent.com/40539079/74111324-d96e0b00-4b61-11ea-92b0-3988aa50246f.png)

**Comment by samiha-rahman** [comment]
Closing as duplicate to #14, which allows the selection of vertical transportation (i.e. elevators for disabled users)
