### ISSUE TITLE
AT-4: Go inside a building from the outdoor map

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#120]
As a user I should be able to go inside a building from the outdoor view.

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
-- | -- | -- | --
1 | Clicking on building | Building Info should pop up |  
2 | Clicking on building | Building Info should have "Go Indoor option" |

**Comment by mosaliza** [comment]
Accepted.
