### ISSUE TITLE
AT-5: UI Navigation Search Bar

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#121]
As a user, I would like to be able to input text to search from one location to another.

**Associated user story:** #88 

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
-- | -- | -- | --
1 | Open the app| There should be an input box for the start location, end location and the mode of transportation.  |  Passed
2 | Go to indoor map | additional options should appear for the vertical mode of transportation (stairs, escalators, elevators) |  Passed
3 | Input in search bar | should provide suggestions |  Passed

**Comment by mosaliza** [comment]
Accepted.
