### ISSUE TITLE
AT 6: Switch campus map

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/soen390#123]
As a user, I want to easily switch between campuses (SGW and Loyola)

Associated story: #1 

**Acceptance Criteria:**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | User opens the outdoor map | Two buttons are **clearly** displayed on the top of the map to toggle between campuses | Passed
2 | Click one of the buttons | Map displays designated campus and surrounding area on the outdoor map view | Passed

**Comment by mosaliza** [comment]
Accepted.
