### ISSUE TITLE
US-27: Navigation menu

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#36]
As a user, I would like to navigate through the app with a navigation menu.
The navigation menu is a place that will allow users to access different features of the app. It will allow users to access:
-application settings
-bus schedule 
-search for a building/classroom 
-view more information about a building 
-floor plans
-upcoming classes
-places of interest
to help make the app easier to navigate.

Acceptance Criteria

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Pull up menu displaying settings and bus options | User should be able click | 

Associated epic:
#35

Associated tasks:

Mockup:
![image.png](https://images.zenhubusercontent.com/5e18d0aa32969d7ce10e5f59/422e5d60-b825-42ba-ad97-57b264b4fe40)

**Comment by Weigiu** [comment]
Acceptance Criteria:
-scroll up menu displaying settings
-display accessibility to bus schedule 
-pull out keyboard for search

**Comment by samiha-rahman** [comment]
@Weigiu Add the acceptance criteria into the description please!

**Comment by Weigiu** [comment]
@samiha-rahman yes madam
