### ISSUE TITLE
US-37: Update file structure

### ISSUE THREAD

**Issue by a-paggabao** [samiha-rahman/soen390#47]
- Organize file structure to integrate the architecture and design of the project.
- Follow [Angular style guide](https://angular.io/guide/styleguide#services).
&nbsp;
**Tasks:**
- [x] Add pages, interfaces, providers folders per ionic-angular style guide.
- [x] Integrate the class diagram to project

**Comment by samiha-rahman** [comment]
PR #48 was merged
