### ISSUE TITLE
US-9: Google Calendar Integration

### ISSUE THREAD

**Issue by david0455** [samiha-rahman/soen390#9]
As a user, I want to connect to Google Calendar to sync my class schedule with the application.

Associated epic:
#19 

Associated tasks:

Mockup:
![image](https://user-images.githubusercontent.com/40539079/74111238-41702180-4b61-11ea-8b15-8e7eeb47c5e8.png)

**Comment by samiha-rahman** [comment]
Closing as duplicate, as the work has been covered in #78.
